repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [push]
        language: system
        entry: poetry run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [push]
        language: system
        entry: poetry run mypy battery_optimization
        types: [python]
        pass_filenames: false

      - id: pytest
        stages: [push]
        name: pytest
        entry: poetry run pytest
        language: system
